server {
    listen 80;

    location / {
        proxy_pass         http://zitadel-api:8080;
        proxy_set_header   Host localhost;
        proxy_read_timeout 30s;
        proxy_send_timeout 30s;
    }
}
