"""
DocIntel — Zitadel Actions v2 webhook: group→role expander.

Zitadel's preaccesstoken/preuserinfo webhook payload does NOT include user
grants. We fetch them from the Management API using the service-account PAT
and cache results per user to avoid redundant calls.

Expanded claims embedded in every JWT:
  tenant_id  — lowercased org name
  role       — highest coarse role (platform_admin > tenant_admin > tenant_user)
  roles      — fine-grained permission array (read by OPA / gateway)
  clearance  — highest clearance level

Environment:
  ZITADEL_ACTIONS_SIGNING_KEY   HMAC key (generated by start.sh).
  ZITADEL_SERVICE_ACCOUNT_PAT   Admin-SA PAT for Management API calls.
  ZITADEL_URL                   Internal Zitadel base URL (default: http://zitadel-api:8080).
  PORT                          Listening port (default: 8090).
"""

import hashlib
import hmac
import json
import logging
import os
import sys
import time
import urllib.error
import urllib.request
from http.server import BaseHTTPRequestHandler, HTTPServer

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [actions-v2] %(levelname)s %(message)s",
    stream=sys.stdout,
)
log = logging.getLogger("actions-v2")

PORT = int(os.environ.get("PORT", "8090"))
ZITADEL_URL = os.environ.get("ZITADEL_URL", "http://zitadel-proxy").rstrip("/")
ZITADEL_HOST = os.environ.get("ZITADEL_HOST", "localhost")
_SIGNING_KEY: str = os.environ.get("ZITADEL_ACTIONS_SIGNING_KEY", "")
_SA_PAT: str = os.environ.get("ZITADEL_SERVICE_ACCOUNT_PAT", "")

# On first boot (before start.sh writes generated.env) the signing key and PAT
# are not available yet.  We start in "pending" mode: the health endpoint returns
# 200 so Zitadel's DNS lookup during target registration resolves the hostname,
# but every POST to /claims returns 503 until the service is restarted with the
# real key.  start.sh restarts us in Phase 6 after writing generated.env.
_KEY_CONFIGURED = bool(_SIGNING_KEY)
if not _KEY_CONFIGURED:
    log.warning(
        "ZITADEL_ACTIONS_SIGNING_KEY not set - starting in key-pending mode. "
        "/claims requests will be rejected (503) until service is restarted with the key."
    )
else:
    log.info("Signing key loaded.")

if not _SA_PAT:
    log.warning("ZITADEL_SERVICE_ACCOUNT_PAT not set — role lookups will return empty.")
else:
    log.info("Service-account PAT loaded.")

# ---------------------------------------------------------------------------
# Static role expansion (IAM source of truth)
# ---------------------------------------------------------------------------

GROUP_ROLES: dict[str, list[str]] = {
    "platform_admin": [
        "documents:r",
        "documents:rw",
        "documents:delete_all",
        "query:execute",
        "conversations:rw",
        "analytics:r",
        "analytics:r_all",
        "analytics:feedback",
        "ingestion:rw",
        "admin:rw",
        "vector_stats:r",
        "models:r",
    ],
    "tenant_admin": [
        "documents:r",
        "documents:rw",
        "documents:delete",
        "query:execute",
        "conversations:rw",
        "analytics:r",
        "analytics:feedback",
        "ingestion:rw",
        "admin.cache:rw",
        "admin.tenants.settings:rw",
        "vector_stats:r",
        "models:r",
    ],
    "tenant_user": [
        "documents:r",
        "query:execute",
        "conversations:rw",
        "analytics:feedback",
        "models:r",
    ],
}

GROUP_CLEARANCE: dict[str, str] = {
    "platform_admin": "restricted",
    "tenant_admin": "confidential",
    "tenant_user": "internal",
}

_ROLE_RANK: dict[str, int] = {"platform_admin": 2, "tenant_admin": 1, "tenant_user": 0}
_CLEARANCE_ORDER = ["public", "internal", "confidential", "restricted"]

# ---------------------------------------------------------------------------
# Simple in-process cache: user_id → (roles_list, expires_at)
# TTL matches access token lifetime (15 min) so role changes take effect on
# the next token issuance after the cache expires.
# ---------------------------------------------------------------------------

_GRANT_CACHE: dict[str, tuple[list[str], float]] = {}
_CACHE_TTL = 900  # seconds


def _fetch_grants_from_api(user_id: str, org_id: str) -> list[str]:
    """Call Zitadel Management API to get coarse roles for a user in an org."""
    if not _SA_PAT:
        return []
    url = f"{ZITADEL_URL}/management/v1/users/grants/_search"
    payload = json.dumps({
        "queries": [{"userIdQuery": {"userId": user_id}}]
    }).encode()
    req = urllib.request.Request(url, data=payload, method="POST")
    req.add_header("Authorization", f"Bearer {_SA_PAT}")
    req.add_header("Host", ZITADEL_HOST)
    req.add_header("x-zitadel-orgid", org_id)
    req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=5) as resp:
            data = json.loads(resp.read())
            roles: list[str] = []
            for grant in data.get("result") or []:
                roles.extend(grant.get("roleKeys") or [])
            return roles
    except urllib.error.URLError as exc:
        log.warning("Management API call failed: %s", exc)
        return []


def get_coarse_roles(user_id: str, org_id: str) -> list[str]:
    """Return coarse roles, using cache when fresh."""
    cached = _GRANT_CACHE.get(user_id)
    if cached and time.monotonic() < cached[1]:
        return cached[0]
    roles = _fetch_grants_from_api(user_id, org_id)
    _GRANT_CACHE[user_id] = (roles, time.monotonic() + _CACHE_TTL)
    return roles


# ---------------------------------------------------------------------------
# Signature verification
# ---------------------------------------------------------------------------

def verify_signature(header: str, raw_body: bytes) -> bool:
    parts = dict(p.split("=", 1) for p in header.split(",") if "=" in p)
    timestamp = parts.get("t")
    received_sig = parts.get("v1")
    if not timestamp or not received_sig:
        log.warning("Malformed signature header: %s", header)
        return False
    signed_payload = f"{timestamp}.".encode() + raw_body
    computed = hmac.new(_SIGNING_KEY.encode(), signed_payload, hashlib.sha256).hexdigest()
    match = hmac.compare_digest(computed, received_sig)
    if not match:
        log.warning("Signature mismatch.")
    return match


# ---------------------------------------------------------------------------
# Claims resolution
# ---------------------------------------------------------------------------

def resolve_claims(body: dict) -> list:
    org = body.get("org") or {}
    # Zitadel sends snake_case in the real preaccesstoken payload
    tenant_id = (
        org.get("name") or org.get("primary_domain") or org.get("primaryDomain") or "default"
    ).lower()
    org_id = org.get("id", "")

    # Payload field for user ID also varies
    user_id = body.get("userId") or (body.get("userinfo") or {}).get("sub") or ""

    # 1. Try grants embedded in payload (works for some Zitadel versions / trigger types)
    coarse_roles: list[str] = []
    for grant in body.get("userGrants") or body.get("user_grants") or []:
        coarse_roles.extend(grant.get("roles") or [])

    # 2. Fallback: fetch from Management API when payload doesn't include grants
    if not coarse_roles and user_id and org_id:
        coarse_roles = get_coarse_roles(user_id, org_id)

    fine_roles: list[str] = list({r for g in coarse_roles for r in GROUP_ROLES.get(g, [])})

    clearance = max(
        (GROUP_CLEARANCE.get(g, "public") for g in coarse_roles),
        key=lambda c: _CLEARANCE_ORDER.index(c) if c in _CLEARANCE_ORDER else -1,
        default="public",
    )

    coarse_role = max(
        coarse_roles or ["tenant_user"],
        key=lambda r: _ROLE_RANK.get(r, -1),
    )

    log.info(
        "tenant=%s user=%s coarse_roles=%s role=%s fine_roles=%d clearance=%s",
        tenant_id, user_id, coarse_roles, coarse_role, len(fine_roles), clearance,
    )

    return [
        {"key": "tenant_id", "value": tenant_id},
        {"key": "role",      "value": coarse_role},
        {"key": "roles",     "value": fine_roles},
        {"key": "clearance", "value": clearance},
    ]


# ---------------------------------------------------------------------------
# HTTP handler
# ---------------------------------------------------------------------------

class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        log.debug(fmt, *args)

    def _respond(self, status: int, body: bytes, content_type: str = "application/json"):
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        if self.path == "/health":
            self._respond(200, b'{"status":"ok"}')
        else:
            self._respond(404, b'{"error":"not found"}')

    def do_POST(self):
        if self.path != "/claims":
            self._respond(404, b'{"error":"not found"}')
            return

        if not _KEY_CONFIGURED:
            self._respond(503, b'{"error":"signing key not yet configured - service pending restart"}')
            return

        length = int(self.headers.get("Content-Length", 0))
        raw_body = self.rfile.read(length)

        sig_header = self.headers.get("zitadel-signature", "")
        if not verify_signature(sig_header, raw_body):
            self._respond(400, b'{"error":"invalid signature"}')
            return

        try:
            body = json.loads(raw_body)
        except json.JSONDecodeError:
            self._respond(400, b'{"error":"invalid json"}')
            return

        claims = resolve_claims(body)
        resp = json.dumps({"append_claims": claims}).encode()
        self._respond(200, resp)


def main():
    server = HTTPServer(("0.0.0.0", PORT), Handler)
    log.info("Listening on :%d  /claims  /health", PORT)
    server.serve_forever()


if __name__ == "__main__":
    main()
