#!/usr/bin/env python3
"""
DocIntel Integration Test Runner
=================================
Loads query suites from queries.yaml, calls the RAG streaming API for each,
and writes a structured JSON report + human-readable Markdown summary.

REQUIRES: Full DocIntel stack running (docker compose up).
          Documents must already be ingested for RAG queries to return results.

Usage:
    # Normal mode — JWT Bearer auth via e2e service account (start.sh writes the key):
    python run_tests.py

    # Run a single suite or save to a specific file:
    python run_tests.py --suite "HR Policies"
    python run_tests.py --out reports/my_run.json

    # Skip auth entirely (only works if security is disabled):
    python run_tests.py --no-auth

Env vars:
    ZITADEL_CLIENT_ID    Zitadel app client_id (from config/zitadel/generated.env)
    DOCINTEL_TEST_USER   override username without exposing in shell history
    DOCINTEL_TEST_PASS   override password
"""

import argparse
import json
import os
import sys
import time
from datetime import datetime
from pathlib import Path

import httpx
import yaml

SCRIPT_DIR = Path(__file__).parent
DEFAULT_CONFIG = SCRIPT_DIR / "queries.yaml"
REPORTS_DIR = SCRIPT_DIR / "reports"


# =============================================================================
# Token acquisition — JWT Bearer Grant (RFC 7523)
#
# Industry-standard approach for service-account auth against OIDC providers
# that don't support ROPC (Zitadel, Okta, Azure AD all dropped it).
#
# Flow:
#   1. Load the E2E SA JSON key (generated by Terraform, written by start.sh)
#   2. Build a short-lived JWT assertion signed with the SA's RSA private key
#   3. POST to /oauth/v2/token with grant_type=jwt-bearer
#   4. Receive a proper access JWT the gateway validates normally
#
# Key file: config/zitadel/e2e-sa-key.json  (auto-generated, git-ignored)
# Format (Zitadel machine user key):
#   { "type": "serviceaccount", "keyId": "...", "key": "-----BEGIN RSA PRIVATE KEY-----...",
#     "appId": "...", "clientId": "user@<instance>.zitadel.cloud" }
# =============================================================================

import uuid as _uuid
from datetime import datetime, timedelta, timezone


def _load_key_file() -> dict:
    """Load the E2E SA key from file path in env or default location."""
    project_root = os.path.realpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "../.."))
    key_file = os.environ.get("E2E_SA_KEY_FILE") or "config/zitadel/e2e-sa-key.json"
    # Relative paths are anchored to the project root, not the script's CWD
    if not os.path.isabs(key_file):
        key_file = os.path.join(project_root, key_file)
    key_path = os.path.realpath(key_file)
    if not os.path.exists(key_path):
        print(
            f"\nERROR: E2E service account key not found at:\n  {key_path}\n\n"
            "Run ./scripts/docintel.sh → Start to (re)generate it.\n"
            "The key is written to config/zitadel/e2e-sa-key.json by start.sh.\n",
            file=sys.stderr,
        )
        sys.exit(1)
    with open(key_path) as f:
        return json.load(f)


def acquire_token(
    auth_cfg: dict,
    username: str | None,        # unused — SA auth needs no username
    password: str | None,        # unused
    client_id: str | None = None,
) -> tuple[str | None, int]:
    """
    Acquire a bearer JWT via JWT Bearer Grant (RFC 7523).
    Returns None only if auth_cfg has no token_url (i.e. auth fully disabled).
    """
    if not auth_cfg.get("token_url"):
        return None, 0

    try:
        import jwt as _jwt                    # PyJWT[crypto]
    except ImportError:
        print(
            "ERROR: PyJWT not installed. Run:\n"
            "  pip install -r tests/integration/requirements.txt\n",
            file=sys.stderr,
        )
        sys.exit(1)

    token_url    = auth_cfg["token_url"]
    zitadel_base = "/".join(token_url.split("/")[:3])

    key_data = _load_key_file()
    private_key = key_data["key"]
    key_id      = key_data["keyId"]
    # Machine user keys use userId as issuer/subject (not clientId — that's for app keys)
    user_id_claim = key_data["userId"]

    now = datetime.now(timezone.utc)
    assertion = _jwt.encode(
        {
            "iss": user_id_claim,
            "sub": user_id_claim,
            "aud": [zitadel_base],   # Zitadel validates aud = issuer (base URL, not token URL)
            "iat": now,
            "exp": now + timedelta(minutes=5),
            "jti": str(_uuid.uuid4()),
        },
        private_key,
        algorithm="RS256",
        headers={"kid": key_id},
    )

    print("Acquiring token via JWT Bearer grant (RFC 7523) …")
    try:
        resp = httpx.post(
            token_url,
            data={
                "grant_type": "urn:ietf:params:oauth:grant-type:jwt-bearer",
                "scope":      auth_cfg.get("scopes", "openid email profile"),
                "assertion":  assertion,
            },
            timeout=30,
        )
        resp.raise_for_status()
        body = resp.json()
        token = body.get("access_token")
        if not token:
            raise ValueError(f"No access_token in response: {resp.text[:200]}")
        expires_in = int(body.get("expires_in", 899))
        print(f"Token acquired (expires_in={expires_in}s)\n")
        return token, expires_in
    except Exception as exc:
        print(f"ERROR: Failed to acquire token — {exc}", file=sys.stderr)
        sys.exit(1)


# =============================================================================
# E2E test environment — setup and teardown
#
# setup_e2e_environment: seeds a small test dataset into the e2e tenant via the
#   ingestion service (direct, port 8001 — requires INTERNAL_GATEWAY_SECRET).
# teardown_e2e_environment: deletes ALL documents from the e2e tenant via the
#   gateway's DELETE /api/v1/documents/all endpoint. Called in a try/finally so
#   it always runs even when tests fail or are interrupted.
# =============================================================================

import hashlib as _hashlib
import hmac as _hmac


def _load_internal_secret() -> str:
    """Load INTERNAL_GATEWAY_SECRET from .env relative to the project root."""
    project_root = os.path.realpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "../.."))
    env_file = os.path.join(project_root, ".env")
    if not os.path.exists(env_file):
        # Fall back to environment variable (e.g. when sourced externally)
        secret = os.environ.get("INTERNAL_GATEWAY_SECRET", "")
        if secret:
            return secret
        print(
            "ERROR: INTERNAL_GATEWAY_SECRET not found.\n"
            f"  Expected .env at: {env_file}\n"
            "  Or set INTERNAL_GATEWAY_SECRET environment variable.\n",
            file=sys.stderr,
        )
        sys.exit(1)
    with open(env_file) as f:
        for line in f:
            line = line.strip()
            if line.startswith("INTERNAL_GATEWAY_SECRET="):
                return line.split("=", 1)[1].strip().strip('"').strip("'")
    secret = os.environ.get("INTERNAL_GATEWAY_SECRET", "")
    if not secret:
        print("ERROR: INTERNAL_GATEWAY_SECRET not set in .env or environment.\n", file=sys.stderr)
        sys.exit(1)
    return secret


def _hmac_token(request_id: str, tenant_id: str, user_id: str, secret: str) -> str:
    msg = f"{request_id}:{tenant_id}:{user_id}".encode()
    return _hmac.new(secret.encode(), msg, _hmac.new.__class__.__mro__[-1]).hexdigest()  # type: ignore[attr-defined]


def _compute_hmac(request_id: str, tenant_id: str, user_id: str, secret: str) -> str:
    msg = f"{request_id}:{tenant_id}:{user_id}".encode()
    return _hmac.new(secret.encode(), msg, _hashlib.sha256).hexdigest()


def _ensure_tenant_exists(base_url: str, tenant_id: str, bearer_token: str) -> None:
    """
    Register the tenant in the admin service if it doesn't already exist.
    Idempotent — 409 Conflict is silently accepted.
    """
    headers = {
        "Authorization": f"Bearer {bearer_token}",
        "X-Tenant-Id": tenant_id,
        "Content-Type": "application/json",
    }
    resp = httpx.post(
        f"{base_url.rstrip('/')}/api/v1/tenants",
        headers=headers,
        json={"id": tenant_id, "name": "E2E Test Tenant"},
        timeout=15,
    )
    if resp.status_code in (200, 201):
        print(f"  ✓ Tenant '{tenant_id}' registered in admin service.")
    elif resp.status_code == 409:
        print(f"  ✓ Tenant '{tenant_id}' already exists.")
    else:
        print(
            f"  ERROR: Failed to register tenant '{tenant_id}': HTTP {resp.status_code}: {resp.text[:200]}",
            file=sys.stderr,
        )
        sys.exit(1)


def setup_e2e_environment(
    tenant_id: str,
    base_url: str = "http://localhost:8080",
    ingestion_url: str = "http://localhost:8001",
    data_loader_url: str = "http://localhost:8003",
    bearer_token: str | None = None,
) -> None:
    """
    Seed test datasets into the e2e tenant via the data-loader service.

    Dataset loading moved from ingestion-service (/ingest/dataset/*) to
    data-loader (/datasets/*) as part of the Phase 1 pipeline redesign.
    The data-loader auth uses X-User-Id (not the HMAC service token).

    Seeds all three suites' datasets so every query suite has documents.
    The 'e2e' tenant is pre-seeded in the DB (config/postgres/init.sql).
    Blocks until the ingestion job completes or raises on error.
    """
    user_id = "e2e-test-runner"

    print("Setup: seeding test datasets into e2e tenant …")
    try:
        resp = httpx.post(
            f"{data_loader_url}/datasets/load",
            headers={
                "Content-Type": "application/json",
                "X-User-Id": user_id,
                "X-Tenant-Id": tenant_id,
            },
            json={"datasets": ["techqa", "hr_policies", "cuad"], "samples_per_dataset": 5},
            timeout=30,
        )
        resp.raise_for_status()
    except Exception as exc:
        print(
            f"ERROR: Failed to start seed job — {exc}\n"
            f"  Is data-loader reachable at {data_loader_url}?\n",
            file=sys.stderr,
        )
        sys.exit(1)

    job_id = resp.json().get("message", "")
    if not job_id:
        print(f"ERROR: Could not parse job_id from seed response: {resp.text[:200]}", file=sys.stderr)
        sys.exit(1)
    print(f"  Seed job started (job_id={job_id})")

    # Stream SSE progress from data-loader until done/error
    success = False
    with httpx.Client(timeout=600) as client:
        with client.stream(
            "GET",
            f"{data_loader_url}/datasets/load/{job_id}/progress",
            headers={
                "X-User-Id": user_id,
                "X-Tenant-Id": tenant_id,
            },
        ) as stream:
            total_docs = 0
            done_docs = 0
            current_event_type = None
            for line in stream.iter_lines():
                # SSE format: "event: {type}" then "data: {json}" then blank line
                if line.startswith("event: "):
                    current_event_type = line[7:].strip()
                    continue
                if not line.startswith("data: "):
                    continue
                try:
                    event = json.loads(line[6:])
                except json.JSONDecodeError:
                    continue
                # Type is from the SSE "event:" field; fall back to JSON body "type" for compat
                etype = current_event_type or event.get("type") or event.get("event")
                current_event_type = None  # reset for next event
                if etype == "total":
                    total_docs = event.get("total", 0)
                elif etype == "progress":
                    done_docs = event.get("processed", done_docs + 1)
                    pct = int(done_docs / total_docs * 100) if total_docs else 0
                    print(f"\r  Ingesting … {done_docs}/{total_docs} ({pct}%)", end="", flush=True)
                elif etype == "done":
                    done_docs = event.get("processed", total_docs)
                    print(f"\r  ✓ Ingested {done_docs} documents into tenant '{tenant_id}'")
                    success = True
                    return
                elif etype == "error":
                    reason = event.get("reason", event)
                    print(f"\nERROR: Seed job failed: {reason}", file=sys.stderr)
                    sys.exit(1)

    if not success:
        print(
            "\nERROR: Seed job stream closed without a 'done' event.\n"
            "  The ingestion job likely failed — check ingestion-service logs.\n",
            file=sys.stderr,
        )
        sys.exit(1)


def teardown_e2e_environment(
    base_url: str,
    tenant_id: str,
    bearer_token: str | None,
) -> None:
    """
    Delete all documents from the e2e tenant by listing then deleting each one.
    Uses the standard authenticated gateway endpoints — no HMAC needed.
    Always called (try/finally) to prevent artifact accumulation.
    """
    print(f"\nTeardown: deleting all documents for tenant '{tenant_id}' …")
    headers: dict[str, str] = {"X-Tenant-Id": tenant_id}
    if bearer_token:
        headers["Authorization"] = f"Bearer {bearer_token}"

    base = base_url.rstrip("/")
    deleted = 0
    errors = 0
    try:
        # Paginate until no more documents remain
        while True:
            resp = httpx.get(
                f"{base}/api/v1/documents",
                headers=headers,
                params={"page": 0, "size": 50},
                timeout=30,
            )
            if resp.status_code != 200:
                print(
                    f"  ⚠  GET /api/v1/documents returned HTTP {resp.status_code} — skipping cleanup.",
                    file=sys.stderr,
                )
                return

            data = resp.json()
            # Spring Page response: {"content": [...], "totalElements": N}
            docs = data.get("content", data if isinstance(data, list) else [])
            if not docs:
                break

            for doc in docs:
                doc_id = doc.get("id") or doc.get("documentId")
                if not doc_id:
                    continue
                del_resp = httpx.delete(
                    f"{base}/api/v1/documents/{doc_id}",
                    headers=headers,
                    timeout=30,
                )
                if del_resp.status_code in (200, 204, 404):
                    deleted += 1
                else:
                    errors += 1

        if errors:
            print(f"  ⚠  Deleted {deleted} docs, {errors} errors. Manual cleanup may be required.")
        else:
            print(f"  ✓ Tenant '{tenant_id}' cleaned up ({deleted} documents deleted).")
    except Exception as exc:
        print(f"  ⚠  Teardown failed (non-fatal): {exc}", file=sys.stderr)


# =============================================================================
# Pre-flight checks
# =============================================================================

class PreFlightError(SystemExit):
    pass


def _check_url(label: str, url: str, timeout: int = 8) -> None:
    try:
        r = httpx.get(url, timeout=timeout, follow_redirects=True)
        if r.status_code >= 500:
            print(
                f"\nERROR: {label} returned HTTP {r.status_code}.\n"
                f"  URL: {url}\n"
                f"  The service may be starting up or misconfigured.\n",
                file=sys.stderr,
            )
            raise PreFlightError(2)
    except httpx.ConnectError:
        print(
            f"\nERROR: Cannot reach {label}.\n"
            f"  URL: {url}\n"
            f"  Is the DocIntel stack running?  ./scripts/docintel.sh → Start\n",
            file=sys.stderr,
        )
        raise PreFlightError(2)
    except httpx.TimeoutException:
        print(
            f"\nERROR: {label} timed out after {timeout}s.\n"
            f"  URL: {url}\n"
            f"  Service may be overloaded or not yet healthy.\n",
            file=sys.stderr,
        )
        raise PreFlightError(2)


def pre_flight(base_url: str, rag_path: str, no_auth: bool, token_url: str | None, tenant_id: str) -> None:
    """Fail fast with a clear message if the stack or Zitadel is unreachable."""
    print("Pre-flight checks …")

    # API Gateway health — always the entry point (rag-service port is not exposed to host)
    gw_health = base_url.rstrip("/") + "/actuator/health"
    _check_url("API Gateway", gw_health)
    print(f"  ✓ API Gateway reachable ({base_url})")

    # Zitadel — only needed when auth is enabled
    if not no_auth and token_url:
        zitadel_base = "/".join(token_url.split("/")[:3])  # http://host:port
        _check_url("Zitadel", zitadel_base + "/debug/healthz")
        print(f"  ✓ Zitadel reachable ({zitadel_base})")

    print()


# =============================================================================
# SSE streaming parser
# =============================================================================

def call_streaming(
    base_url: str,
    rag_path: str,
    question: str,
    document_type: str,
    tenant_id: str,
    use_reranking: bool,
    use_cache: bool,
    timeout: int,
    bearer_token: str | None = None,
    extra_payload: dict | None = None,
) -> dict:
    """Call the RAG streaming endpoint, collect all SSE events and return a result dict."""
    payload: dict = {
        "question": question,
        "tenant_id": tenant_id,
        "document_type": document_type,
        "use_reranking": use_reranking,
        "use_cache": use_cache,
    }
    if extra_payload:
        payload.update(extra_payload)

    headers = {
        "Content-Type": "application/json",
        "Accept": "text/event-stream",
        "X-Tenant-Id": tenant_id,
    }
    if bearer_token:
        headers["Authorization"] = f"Bearer {bearer_token}"

    answer = ""
    thinking = ""
    sources = []
    error = None
    cache_hit = False
    t0 = time.time()

    try:
        with httpx.Client(timeout=timeout) as client:
            with client.stream(
                "POST",
                f"{base_url}{rag_path}",
                json=payload,
                headers=headers,
            ) as resp:
                resp.raise_for_status()
                buffer = ""
                for raw_chunk in resp.iter_text():
                    buffer += raw_chunk
                    while "\n" in buffer:
                        line, buffer = buffer.split("\n", 1)
                        line = line.strip()
                        if not line.startswith("data: "):
                            continue
                        try:
                            data = json.loads(line[6:])
                        except json.JSONDecodeError:
                            continue
                        if "metadata" in data:
                            meta = data["metadata"]
                            cache_hit = bool(meta.get("cache_hit", False))
                        if data.get("thinking_token"):
                            thinking += data["thinking_token"]
                        if data.get("token"):
                            answer += data["token"]
                        if data.get("sources"):
                            sources = data["sources"]
                        if data.get("cache_hit"):
                            cache_hit = True
                        if data.get("error"):
                            error = data["error"]
                        if data.get("done"):
                            break
    except Exception as exc:
        error = str(exc)

    latency = round(time.time() - t0, 2)
    return {
        "answer": answer.strip(),
        "thinking_length": len(thinking),
        "sources": sources,
        "source_count": len(sources),
        "latency_seconds": latency,
        "error": error,
        "cache_hit": cache_hit,
    }


# =============================================================================
# Evaluation
# =============================================================================

def evaluate(
    result: dict,
    expect_keywords: list[str],
    min_answer_length: int = 5,
    expect_no_sources: bool = False,
    expect_thinking_length_min: int | None = None,
    expect_cache_hit: bool = False,
) -> dict:
    """
    Evaluate a streaming result against expectations.

    expect_no_sources        : pass when sources list is empty (min score strict mode).
    expect_thinking_length_min: pass only when thinking token count >= this value.
    expect_cache_hit         : pass only when the metadata cache_hit flag is True.
    """
    answer = result["answer"].lower()

    # Check keywords in both answer AND source content so that a short but
    # factually correct answer (e.g. "Garman [4]") is not penalised when the
    # keyword appears in the retrieved source chunks.
    source_text = " ".join(
        (s.get("content") or "") for s in result.get("sources", [])
    ).lower()
    combined = answer + " " + source_text

    keyword_hits = [kw for kw in expect_keywords if kw.lower() in combined]
    keyword_miss = [kw for kw in expect_keywords if kw.lower() not in combined]

    if expect_no_sources:
        # No-sources mode: answer must be non-empty, sources must be empty.
        sources_ok = result["source_count"] == 0
    else:
        sources_ok = result["source_count"] > 0

    thinking_ok = True
    if expect_thinking_length_min is not None:
        thinking_ok = result.get("thinking_length", 0) >= expect_thinking_length_min

    cache_hit_ok = True
    if expect_cache_hit:
        cache_hit_ok = bool(result.get("cache_hit", False))

    passed = (
        result["error"] is None
        and len(result["answer"]) >= min_answer_length
        and sources_ok
        and len(keyword_miss) == 0
        and thinking_ok
        and cache_hit_ok
    )

    return {
        "passed": passed,
        "keyword_hits": keyword_hits,
        "keyword_miss": keyword_miss,
        "keyword_coverage": (
            round(len(keyword_hits) / len(expect_keywords), 2)
            if expect_keywords else 1.0
        ),
        "answer_length": len(result["answer"]),
        "thinking_length": result.get("thinking_length", 0),
        "cache_hit": result.get("cache_hit", False),
    }


# =============================================================================
# Report writers
# =============================================================================

PASS = "✅"
FAIL = "❌"
WARN = "⚠️"


def write_markdown(report: dict, path: Path) -> None:
    lines = [
        f"# DocIntel Integration Test Report",
        f"",
        f"**Run at:** {report['run_at']}  ",
        f"**Base URL:** {report['config']['base_url']}  ",
        f"**Total:** {report['summary']['total']} queries | "
        f"{report['summary']['passed']} passed | "
        f"{report['summary']['failed']} failed  ",
        f"",
    ]

    for suite in report["suites"]:
        suite_pass = sum(1 for q in suite["queries"] if q["eval"]["passed"])
        suite_total = len(suite["queries"])
        lines += [
            f"---",
            f"",
            f"## {suite['name']}  `{suite['document_type']}`  "
            f"({suite_pass}/{suite_total} passed)",
            f"",
        ]
        for q in suite["queries"]:
            ev = q["eval"]
            res = q["result"]
            icon = PASS if ev["passed"] else FAIL
            kw_note = ""
            if q["expect_keywords"]:
                hit_pct = int(ev["keyword_coverage"] * 100)
                kw_note = f" | kw {hit_pct}%"
                if ev["keyword_miss"]:
                    kw_note += f" (missing: {', '.join(ev['keyword_miss'])})"
            lines += [
                f"### {icon} {q['question']}",
                f"",
                f"*{res['latency_seconds']}s · {res['source_count']} sources{kw_note}*",
                f"",
            ]
            if res["error"]:
                lines += [f"> **Error:** {res['error']}", f""]
            elif res["answer"]:
                # Trim to 600 chars for readability
                preview = res["answer"][:600]
                if len(res["answer"]) > 600:
                    preview += "…"
                lines += [f"{preview}", f""]

            if res["sources"]:
                lines.append("**Sources:**")
                for s in res["sources"][:3]:
                    score_pct = int((s.get("score") or 0) * 100)
                    lines.append(
                        f"- [{s.get('ref_id', '?')}] `{s.get('filename', '')}` "
                        f"— {s.get('section', '')} ({score_pct}%)"
                    )
                lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def write_json(report: dict, path: Path) -> None:
    path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")


# =============================================================================
# Main
# =============================================================================

def main() -> int:
    parser = argparse.ArgumentParser(description="DocIntel integration test runner")
    parser.add_argument("--config", default=str(DEFAULT_CONFIG), help="Path to queries.yaml")
    parser.add_argument("--url", help="Override base_url from config")
    parser.add_argument("--rag-path", dest="rag_path", help="Override rag_path from config")
    parser.add_argument("--suite", help="Run only this suite name")
    parser.add_argument("--out", help="Output file prefix (no extension); default: reports/TIMESTAMP")
    parser.add_argument("--no-cache", dest="no_cache", action="store_true", help="Force use_cache=false")
    parser.add_argument(
        "--key-file", dest="key_file",
        help="Path to E2E SA JSON key (default: config/zitadel/e2e-sa-key.json or E2E_SA_KEY_FILE env)",
    )
    parser.add_argument("--no-auth", dest="no_auth", action="store_true", help="Skip token acquisition (direct RAG service)")
    parser.add_argument("--no-setup", dest="no_setup", action="store_true",
                        help="Skip dataset seeding and teardown (use when data is already ingested)")
    parser.add_argument("--ingestion-url", dest="ingestion_url", default="http://localhost:8001",
                        help="Ingestion service URL (default: http://localhost:8001)")
    parser.add_argument("--data-loader-url", dest="data_loader_url", default="http://localhost:8002",
                        help="Data-loader service URL for dataset seeding (default: http://localhost:8002)")
    args = parser.parse_args()

    config_path = Path(args.config)
    if not config_path.exists():
        print(f"Config not found: {config_path}", file=sys.stderr)
        return 1

    cfg = yaml.safe_load(config_path.read_text())
    run_cfg = cfg["config"]

    base_url  = args.url or run_cfg["base_url"]
    rag_path  = args.rag_path or run_cfg.get("rag_path", "/api/v1/query/stream")
    tenant_id = run_cfg.get("tenant_id", "default")
    use_cache = not args.no_cache and run_cfg.get("use_cache", False)
    use_reranking = run_cfg.get("use_reranking", True)
    timeout   = run_cfg.get("timeout_seconds", 120)
    min_answer_length = run_cfg.get("min_answer_length", 5)

    # Token acquisition — skipped if --no-auth or no auth config present
    bearer_token: str | None = None
    _token_acquired_at: float = 0.0
    _token_expires_in: int = 899  # conservative default; overridden from Zitadel response
    auth_cfg = run_cfg.get("auth", {})
    if not args.no_auth and auth_cfg:
        if getattr(args, "key_file", None):
            os.environ["E2E_SA_KEY_FILE"] = args.key_file
        bearer_token, _token_expires_in = acquire_token(auth_cfg, None, None)
        _token_acquired_at = time.time()

    # Pre-flight: fail fast if the stack is not reachable
    pre_flight(
        base_url=base_url,
        rag_path=rag_path,
        no_auth=args.no_auth,
        token_url=auth_cfg.get("token_url") if auth_cfg else None,
        tenant_id=tenant_id,
    )

    suites = cfg["suites"]
    if args.suite:
        suites = [s for s in suites if s["name"] == args.suite]
        if not suites:
            print(f"Suite '{args.suite}' not found.", file=sys.stderr)
            return 1

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_prefix = Path(args.out) if args.out else REPORTS_DIR / timestamp

    report: dict = {
        "run_at": datetime.now().isoformat(),
        "config": {
            "base_url": base_url,
            "rag_path": rag_path,
            "tenant_id": tenant_id,
            "use_cache": use_cache,
            "use_reranking": use_reranking,
            "authenticated": bearer_token is not None,
        },
        "suites": [],
        "summary": {"total": 0, "passed": 0, "failed": 0},
    }

    # Setup: seed test data into the isolated e2e tenant
    no_setup = args.no_setup or os.environ.get("E2E_NO_SETUP", "").lower() in ("1", "true")
    data_loader_url = getattr(args, "data_loader_url", "http://localhost:8002")

    if not no_setup:
        setup_e2e_environment(tenant_id=tenant_id, data_loader_url=data_loader_url)
        print()

    print(f"\nDocIntel Integration Tests — {base_url}{rag_path}")
    print(f"{'─' * 70}\n")

    total = passed = 0

    try:
        for suite_def in suites:
            suite_name = suite_def["name"]
            doc_type   = suite_def.get("document_type", "general")

            # skip_if_env_missing: skip the whole suite unless all listed env vars are set
            skip_vars = suite_def.get("skip_if_env_missing", [])
            if skip_vars and not all(os.environ.get(v) for v in skip_vars):
                print(f"   ⏭  Suite '{suite_name}' skipped (requires env: {', '.join(skip_vars)})")
                continue

            # config_overrides: per-suite overrides (e.g. thinking: true, use_cache: true)
            cfg_overrides = suite_def.get("config_overrides", {})
            suite_use_cache = cfg_overrides.get("use_cache", use_cache)
            # extra_payload carries engine-specific params (thinking) not in the standard schema
            extra_payload: dict = {}
            if "thinking" in cfg_overrides:
                extra_payload["thinking"] = cfg_overrides["thinking"]

            print(f"▶  Suite: {suite_name}  ({doc_type})")

            suite_result = {
                "name": suite_name,
                "document_type": doc_type,
                "queries": [],
            }

            for qdef in suite_def["queries"]:
                question = qdef["question"]
                expect_kw = qdef.get("expect_keywords", [])
                expect_no_sources = bool(qdef.get("expect_no_sources", False))
                expect_thinking_min = qdef.get("expect_thinking_length_min")
                expect_cache_hit = bool(qdef.get("expect_cache_hit", False))

                # Refresh token if expiry is within 2 minutes (checked per-query
                # because individual LLM responses can take 2-4 minutes each)
                if bearer_token is not None and auth_cfg:
                    elapsed = time.time() - _token_acquired_at
                    if elapsed > (_token_expires_in - 120):
                        print("\n⟳  Refreshing bearer token (expiry approaching) …")
                        bearer_token, _token_expires_in = acquire_token(auth_cfg, None, None)
                        _token_acquired_at = time.time()

                # Cache hit test: fire query twice; evaluate the second response
                if expect_cache_hit:
                    print(f"   ⋯  [warm] {question[:55]}", end="", flush=True)
                    call_streaming(
                        base_url=base_url, rag_path=rag_path, question=question,
                        document_type=doc_type, tenant_id=tenant_id,
                        use_reranking=use_reranking, use_cache=suite_use_cache,
                        timeout=timeout, bearer_token=bearer_token, extra_payload=extra_payload,
                    )

                print(f"   ⋯  {question[:65]}", end="", flush=True)
                result = call_streaming(
                    base_url=base_url,
                    rag_path=rag_path,
                    question=question,
                    document_type=doc_type,
                    tenant_id=tenant_id,
                    use_reranking=use_reranking,
                    use_cache=suite_use_cache,
                    timeout=timeout,
                    bearer_token=bearer_token,
                    extra_payload=extra_payload or None,
                )
                ev = evaluate(
                    result, expect_kw,
                    min_answer_length=min_answer_length,
                    expect_no_sources=expect_no_sources,
                    expect_thinking_length_min=expect_thinking_min,
                    expect_cache_hit=expect_cache_hit,
                )

                icon = PASS if ev["passed"] else FAIL
                kw_info = ""
                if expect_kw:
                    kw_info = f" kw={int(ev['keyword_coverage']*100)}%"
                if expect_thinking_min is not None:
                    kw_info += f" think={ev['thinking_length']}"
                if expect_cache_hit:
                    kw_info += f" cache={'HIT' if ev['cache_hit'] else 'MISS'}"
                print(f"\r   {icon}  {question[:60]:<60} {result['latency_seconds']:5.1f}s  "
                      f"{result['source_count']} src{kw_info}")

                suite_result["queries"].append({
                    "question": question,
                    "expect_keywords": expect_kw,
                    "result": result,
                    "eval": ev,
                })
                total += 1
                if ev["passed"]:
                    passed += 1

            report["suites"].append(suite_result)
            print()

    finally:
        # Teardown: always clean up test artifacts regardless of pass/fail
        if not no_setup:
            # Ensure token is valid before teardown
            if bearer_token is not None and auth_cfg:
                elapsed = time.time() - _token_acquired_at
                if elapsed > (_token_expires_in - 120):
                    print("⟳  Refreshing bearer token before teardown …")
                    try:
                        bearer_token, _token_expires_in = acquire_token(auth_cfg, None, None)
                        _token_acquired_at = time.time()
                    except SystemExit:
                        pass
            teardown_e2e_environment(
                base_url=base_url,
                tenant_id=tenant_id,
                bearer_token=bearer_token,
            )

    report["summary"] = {
        "total": total,
        "passed": passed,
        "failed": total - passed,
    }

    json_path = Path(str(out_prefix) + ".json")
    md_path   = Path(str(out_prefix) + ".md")
    write_json(report, json_path)
    write_markdown(report, md_path)

    print(f"{'─' * 70}")
    print(f"Results: {passed}/{total} passed")
    print(f"JSON  → {json_path}")
    print(f"MD    → {md_path}\n")

    return 0 if passed == total else 1


if __name__ == "__main__":
    sys.exit(main())
