#!/bin/bash
# scripts/lib/setup-common.sh
# ============================
# Engine-agnostic setup steps shared by all setup scripts (setup.sh, setup-lmforge.sh, etc.).
#
# Usage — source this from an engine-specific setup script:
#   source "$SCRIPT_DIR/lib/setup-common.sh"
#
# Then call the functions you need:
#   setup_common_prereqs        — check docker, compose, tofu, jq, openssl
#   setup_common_zitadel_keys   — generate RSA key pair for Zitadel System API
#   setup_common_env            — create .env, INTERNAL_GATEWAY_SECRET, generated.env stub
#   setup_common_docker_pull    — docker compose pull
#
# Requires: PROJECT_DIR to be set by the caller before sourcing.

# Guard against double-sourcing
[ -n "$_SETUP_COMMON_LOADED" ] && return 0
_SETUP_COMMON_LOADED=1

# ── Colours & helpers ──────────────────────────────────────────────────────────

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

ok()   { echo -e "  ${GREEN}✓${NC} $*"; }
warn() { echo -e "  ${YELLOW}⚠${NC}  $*"; }
fail() { echo -e "  ${RED}✗${NC} $*" >&2; exit 1; }

check_cmd() {
    local cmd="$1" install_hint="$2"
    if command -v "$cmd" &>/dev/null; then
        ok "$cmd"
    else
        echo "  ✗ $cmd — not found"
        [ -n "$install_hint" ] && echo "    Install: $install_hint"
        prereq_ok=false
    fi
}

# ── setup_common_prereqs ───────────────────────────────────────────────────────
# Checks Docker, Docker Compose, tofu, jq, openssl.
# Engine-specific checks (ollama/lmforge) are left to each setup script.

setup_common_prereqs() {
    echo ""
    echo "================================================"
    echo "Checking Prerequisites"
    echo "================================================"

    prereq_ok=true

    check_cmd docker  "https://www.docker.com/products/docker-desktop/"
    check_cmd tofu    "macOS: brew install opentofu | Linux: https://opentofu.org/docs/intro/install/"
    check_cmd jq      "macOS: brew install jq | Linux: apt install jq / yum install jq"
    check_cmd openssl "macOS: brew install openssl | Linux: apt install openssl"

    if ! docker compose version &>/dev/null; then
        echo "  ✗ docker compose — plugin not available. Update Docker Desktop."
        prereq_ok=false
    else
        ok "docker compose"
    fi

    if [ "$prereq_ok" = false ]; then
        echo ""
        echo "Install the missing tools above, then re-run setup."
        exit 1
    fi

    echo ""
}

# ── setup_common_zitadel_keys ─────────────────────────────────────────────────
# Generates RSA-4096 key pair for Zitadel System API JWT authentication.
# Idempotent — skips if keys already exist.

setup_common_zitadel_keys() {
    local key_dir="$PROJECT_DIR/config/zitadel"
    local private_key="$key_dir/system-api-private.pem"
    local public_key="$key_dir/system-api-public.pem"

    echo ""
    echo "================================================"
    echo "Zitadel System API Key Pair"
    echo "================================================"

    if [ ! -f "$private_key" ]; then
        echo "Generating RSA-4096 key pair..."
        openssl genrsa -out "$private_key" 4096 2>/dev/null
        openssl rsa -in "$private_key" -pubout -out "$public_key" 2>/dev/null
        chmod 600 "$private_key"
        ok "Private key: config/zitadel/system-api-private.pem (gitignored)"
        ok "Public key:  config/zitadel/system-api-public.pem"
    else
        ok "Key pair already exists — skipping."
    fi
}

# ── setup_common_env ──────────────────────────────────────────────────────────
# 1. Creates .env from .env.example if missing.
# 2. Generates INTERNAL_GATEWAY_SECRET if not set.
# 3. Creates stub generated.env so `docker compose` can load the full project
#    config before start.sh writes the real Terraform values on first boot.

setup_common_env() {
    local env_file="$PROJECT_DIR/.env"
    local generated_env="$PROJECT_DIR/config/zitadel/generated.env"

    # .env -----------------------------------------------------------------------
    if [ ! -f "$env_file" ]; then
        echo ""
        echo "================================================"
        echo "Creating .env"
        echo "================================================"
        cp "$PROJECT_DIR/.env.example" "$env_file"
        echo ""
        echo "  IMPORTANT: Edit .env and set:"
        echo "    ZITADEL_MASTERKEY=<exactly 32 chars>   (generate: openssl rand -hex 16)"
        echo ""
        echo "  ZITADEL_CLIENT_ID, ZITADEL_SERVICE_ACCOUNT_PAT, and"
        echo "  ZITADEL_ACTIONS_SIGNING_KEY are auto-generated by start.sh via"
        echo "  Terraform and written to config/zitadel/generated.env."
        echo ""
    else
        echo ""
        ok ".env already exists — skipping."
    fi

    # INTERNAL_GATEWAY_SECRET ----------------------------------------------------
    echo ""
    echo "================================================"
    echo "Internal Gateway Secret"
    echo "================================================"

    if grep -q "^INTERNAL_GATEWAY_SECRET=.\+" "$env_file" 2>/dev/null; then
        ok "INTERNAL_GATEWAY_SECRET already set — skipping."
    else
        local secret
        secret=$(openssl rand -hex 32)
        if grep -q "^INTERNAL_GATEWAY_SECRET=" "$env_file" 2>/dev/null; then
            sed -i.bak "s/^INTERNAL_GATEWAY_SECRET=.*/INTERNAL_GATEWAY_SECRET=$secret/" "$env_file" \
                && rm -f "$env_file.bak"
        else
            echo "INTERNAL_GATEWAY_SECRET=$secret" >> "$env_file"
        fi
        ok "Generated INTERNAL_GATEWAY_SECRET (32-byte hex) → .env"
    fi

    # generated.env stub ---------------------------------------------------------
    if [ ! -f "$generated_env" ]; then
        echo ""
        echo "Creating stub config/zitadel/generated.env..."
        mkdir -p "$(dirname "$generated_env")"
        cat > "$generated_env" <<'STUB'
# Auto-generated by start.sh via Terraform — do not edit manually.
# This stub allows `docker compose` commands to run before first boot.
ZITADEL_CLIENT_ID=
ZITADEL_SERVICE_ACCOUNT_PAT=
ZITADEL_PROJECT_ID=
ZITADEL_ACTIONS_SIGNING_KEY=
STUB
        ok "Stub written → config/zitadel/generated.env"
    else
        ok "generated.env already exists — skipping."
    fi
}

# ── setup_common_docker_pull ──────────────────────────────────────────────────
# Pulls all Docker images declared in docker-compose.yml without starting containers.

setup_common_docker_pull() {
    echo ""
    echo "================================================"
    echo "Pulling Docker Images"
    echo "================================================"

    docker compose pull

    ok "Docker images pulled."
}
