#!/bin/bash
# DocIntel Cleanup Script
# =======================
# Stops AND removes all DocIntel containers.
# Optionally removes volumes (data) and Ollama models.
#
# Use ./scripts/stop.sh if you just want to stop (not remove) containers.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Load model defaults (single source of truth)
# shellcheck source=../config/defaults.env
source "$PROJECT_DIR/config/defaults.env"

echo "================================================"
echo "DocIntel Cleanup"
echo "================================================"
echo ""

REMOVE_MODELS=false
REMOVE_VOLUMES=false
DATA_ONLY=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --all)
            REMOVE_MODELS=true
            REMOVE_VOLUMES=true
            shift
            ;;
        --data)
            DATA_ONLY=true
            shift
            ;;
        --models)
            REMOVE_MODELS=true
            shift
            ;;
        --volumes)
            REMOVE_VOLUMES=true
            shift
            ;;
        -h|--help)
            echo "Usage: ./cleanup.sh [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --data      Wipe all data volumes only (Qdrant, Postgres, Redis, MinIO)"
            echo "              Keeps Docker images and Ollama models intact."
            echo "  --all       Remove containers, volumes, AND Ollama models"
            echo "  --models    Remove only Ollama models"
            echo "  --volumes   Remove containers AND Docker volumes (data loss!)"
            echo "  -h, --help  Show this help message"
            echo ""
            echo "Default (no options): Stops and removes containers only (preserves data)"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "Use --help for usage information."
            exit 1
            ;;
    esac
done

# =============================================================================
# Stop and Remove Docker Containers
# =============================================================================

echo "Stopping and removing Docker containers (all profiles)..."
# Must specify all profiles to stop all containers
docker compose down 2>/dev/null || true
echo "Containers removed."

# =============================================================================
# Wipe Data Volumes Only (--data)
# =============================================================================

if [ "$DATA_ONLY" = true ]; then
    echo ""
    echo "WARNING: This will delete all application data (Qdrant, PostgreSQL, Redis, MinIO, ClickHouse)."
    echo "Docker images and Ollama models are preserved."
    read -p "Are you sure? (y/N): " confirm

    if [[ "$confirm" =~ ^[Yy]$ ]]; then
        echo "Removing data volumes..."
        for vol in qdrant-data postgres-data redis-data minio-data clickhouse-data clickhouse-logs huggingface-cache docling-cache; do
            docker volume rm "docintel_${vol}" 2>/dev/null && echo "  removed docintel_${vol}" || echo "  skipped docintel_${vol} (not found)"
        done
        echo "Data volumes removed."

        # Reset Terraform state (must match wiped Docker volumes or next tofu apply breaks)
        echo "Resetting Terraform state..."
        rm -f "$PROJECT_DIR/terraform/stacks/infra/terraform.tfstate" \
              "$PROJECT_DIR/terraform/stacks/infra/terraform.tfstate.backup" \
              "$PROJECT_DIR/terraform/stacks/identity/terraform.tfstate" \
              "$PROJECT_DIR/terraform/stacks/identity/terraform.tfstate.backup" 2>/dev/null || true

        # Reset generated runtime config files
        echo "Resetting generated runtime config..."
        rm -f "$PROJECT_DIR/config/zitadel/actions-target-id" \
              "$PROJECT_DIR/config/zitadel/actions-signing-key" 2>/dev/null || true
        # Reset generated.env to empty stub so Docker Compose still starts
        cat > "$PROJECT_DIR/config/zitadel/generated.env" <<'EOF'
# Auto-generated by start.sh after terraform apply — do not edit manually.
# Run ./scripts/start.sh to regenerate.
ZITADEL_CLIENT_ID=
ZITADEL_PROJECT_ID=
ZITADEL_SERVICE_ACCOUNT_PAT=
ZITADEL_ACTIONS_SIGNING_KEY=
EOF
        echo "Terraform state and generated config reset."

        # Prune stopped containers, unused networks, dangling images.
        # Deliberately skips build cache — uv/Gradle cache mounts are build-tool
        # caches (equivalent to ~/.gradle / ~/.m2) and should survive data resets.
        echo ""
        echo "Pruning dangling Docker resources (preserving build cache)..."
        docker container prune -f 2>/dev/null || true
        docker image prune -f 2>/dev/null || true
        docker network prune -f 2>/dev/null || true
        echo "Docker prune complete."
    else
        echo "Skipped."
    fi

    echo ""
    echo "================================================"
    echo "Cleanup Complete"
    echo "================================================"
    echo ""
    echo "  [x] Docker containers removed"
    echo "  [x] Data volumes wiped"
    echo "  [x] Dangling images / build cache pruned"
    echo "  [ ] Named Docker images preserved"
    echo "  [ ] Ollama models preserved"
    echo ""
    echo "Commands:"
    echo "  ./scripts/start.sh    # Start fresh"
    echo ""
    exit 0
fi

if [ "$REMOVE_VOLUMES" = true ]; then
    echo ""
    echo "WARNING: This will delete ALL data (PostgreSQL, Qdrant, Redis, MinIO, Zitadel)!"
    read -p "Are you sure? (y/N): " confirm
    
    if [[ "$confirm" =~ ^[Yy]$ ]]; then
        echo "Removing Docker volumes..."
        docker compose down -v 2>/dev/null || true
        
        # Also remove any orphaned volumes with docintel prefix
        docker volume ls -q | grep -E "^docintel" | xargs -r docker volume rm 2>/dev/null || true
        
        echo "Docker volumes removed."

        # Reset Terraform state
        echo "Resetting Terraform state..."
        rm -f "$PROJECT_DIR/terraform/stacks/infra/terraform.tfstate" \
              "$PROJECT_DIR/terraform/stacks/infra/terraform.tfstate.backup" \
              "$PROJECT_DIR/terraform/stacks/identity/terraform.tfstate" \
              "$PROJECT_DIR/terraform/stacks/identity/terraform.tfstate.backup" 2>/dev/null || true

        # Reset generated runtime config files
        echo "Resetting generated runtime config..."
        rm -f "$PROJECT_DIR/config/zitadel/actions-target-id" \
              "$PROJECT_DIR/config/zitadel/actions-signing-key" \
              "$PROJECT_DIR/config/zitadel/system-api-private.pem" 2>/dev/null || true
        cat > "$PROJECT_DIR/config/zitadel/generated.env" <<'EOF'
# Auto-generated by start.sh after terraform apply — do not edit manually.
# Run ./scripts/start.sh to regenerate.
ZITADEL_CLIENT_ID=
ZITADEL_PROJECT_ID=
ZITADEL_SERVICE_ACCOUNT_PAT=
ZITADEL_ACTIONS_SIGNING_KEY=
EOF
        echo "Terraform state and generated config reset."
        
        # Prune unused images and networks — but NOT build cache.
        # Build cache (uv/Gradle cache mounts) lives in Docker's BuildKit storage,
        # not in named volumes. Clearing it here would force a full dep re-download
        # on next build. Use 'docker builder prune' explicitly if you want that.
        echo ""
        echo "Pruning unused images and networks (preserving build cache)..."
        docker image prune -f -a 2>/dev/null || true
        docker network prune -f 2>/dev/null || true
        echo "Docker cleanup complete."
    else
        echo "Skipped volume removal."
    fi
fi

# =============================================================================
# Remove Ollama Models
# =============================================================================

if [ "$REMOVE_MODELS" = true ]; then
    echo ""
    echo "================================================"
    echo "Removing Ollama Models"
    echo "================================================"
    echo ""
    echo "This will free up approximately 8-10GB of disk space."
    echo ""
    
    MODELS=("$DEFAULT_LLM_MODEL" "$DEFAULT_FALLBACK_MODEL" "$DEFAULT_EMBED_MODEL")
    
    # Check if Ollama is available
    if ! command -v ollama &> /dev/null; then
        echo "Ollama CLI not found. Models may need to be removed manually."
        echo ""
        echo "Manual removal locations:"
        echo "  macOS: rm -rf ~/.ollama/models"
        echo "  Linux: rm -rf ~/.ollama/models"
        echo ""
    else
        for model in "${MODELS[@]}"; do
            echo "Removing ${model}..."
            if ollama list 2>/dev/null | grep -q "${model}"; then
                ollama rm "${model}" 2>/dev/null || echo "  Warning: Could not remove ${model}"
            else
                echo "  ${model} not found, skipping."
            fi
        done
        echo ""
        echo "Models removed."
    fi
fi

# =============================================================================
# Summary
# =============================================================================

echo ""
echo "================================================"
echo "Cleanup Complete"
echo "================================================"
echo ""
echo "Removed:"
echo "  [x] Docker containers (stopped and removed)"
if [ "$REMOVE_VOLUMES" = true ]; then
    echo "  [x] Docker volumes (all data deleted)"
    echo "  [x] Docker system prune (images, build cache cleaned)"
else
    echo "  [ ] Docker volumes (data preserved, use --volumes to remove)"
fi
if [ "$REMOVE_MODELS" = true ]; then
    echo "  [x] Ollama models (~8-10GB freed)"
else
    echo "  [ ] Ollama models (use --all or --models to remove)"
fi
echo ""

# Show remaining disk usage if possible
if [ "$REMOVE_MODELS" = false ] && command -v ollama &> /dev/null; then
    echo "Disk usage by Ollama models:"
    du -sh ~/.ollama 2>/dev/null || echo "  Unable to calculate"
    echo ""
fi

echo "Commands:"
echo "  ./scripts/start.sh            # Start fresh (will recreate containers)"
echo "  ./scripts/cleanup.sh --data   # Wipe data only (keeps images + models)"
echo "  ./scripts/setup.sh            # Re-pull images if needed"
echo ""
