#!/bin/bash
# DocIntel Start Script
# =====================
# Usage:
#   ./scripts/start.sh          # Start all services (runs Terraform provisioning if needed)
#   ./scripts/start.sh --build  # Rebuild images before starting

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

source "$PROJECT_DIR/config/defaults.env"
# .env overrides defaults (LLM_ENGINE, LLM_MODEL, LLM_CHAT_URL, etc.)
[ -f "$PROJECT_DIR/.env" ] && source "$PROJECT_DIR/.env"
cd "$PROJECT_DIR"

DO_BUILD=false
for arg in "$@"; do
    case $arg in
        --build) DO_BUILD=true; shift ;;
    esac
done

# ==============================================================================
# Hardware profile — read (never re-detect at start time; build.sh already did)
# ==============================================================================

# shellcheck source=lib/profile_config.sh
source "${SCRIPT_DIR}/lib/profile_config.sh"
read_profile

# Export torch vars so docker compose can resolve ${PROFILE_TAG} in image: fields
torch_vars_for_profile "$PROFILE"

# Build compose file chain: base + GPU overlay when profile != cpu
COMPOSE_FILES="-f docker-compose.yml"
if [ "$PROFILE" != "cpu" ]; then
    if [ -f "${PROJECT_DIR}/docker-compose.gpu.yml" ]; then
        COMPOSE_FILES="${COMPOSE_FILES} -f docker-compose.gpu.yml"
    fi
fi

echo "  [hardware] profile=${PROFILE} source=${PROFILE_SOURCE}"

log()  { echo "  $*"; }
ok()   { echo "  ✓ $*"; }
fail() { echo "  ✗ $*" >&2; exit 1; }

echo "================================================"
echo "  Starting DocIntel"
echo "================================================"
echo ""

# =============================================================================
# Prerequisite checks
# =============================================================================

if ! command -v tofu &> /dev/null; then
    fail "tofu (OpenTofu) is not installed. macOS: brew install opentofu | Linux: https://opentofu.org/docs/intro/install/"
fi

if ! command -v jq &> /dev/null; then
    fail "jq is not installed. Install: brew install jq (macOS) or apt install jq (Linux)"
fi

# Verify RSA key pair exists (generated by setup.sh)
if [ ! -f "config/zitadel/system-api-private.pem" ] || [ ! -f "config/zitadel/system-api-public.pem" ]; then
    fail "Zitadel System API key pair missing. Run ./scripts/setup.sh first."
fi

# Check LLM Engine
LLM_ENGINE="${LLM_ENGINE:-ollama}"
case "$LLM_ENGINE" in
# ── Ollama (default) ─────────────────────────────────────────────────────────
ollama)
    if ! curl -s http://localhost:11434/api/tags > /dev/null 2>&1; then
        echo "Warning: Ollama is not running!"
        if command -v ollama &> /dev/null; then
            echo "  - On macOS: Open the Ollama app from Applications"
            echo "  - On Linux: Run 'ollama serve' in a separate terminal"
            echo ""
            read -p "Press Enter once Ollama is running, or Ctrl+C to abort..."
            if ! curl -s http://localhost:11434/api/tags > /dev/null 2>&1; then
                fail "Ollama still not responding. Aborting."
            fi
        else
            fail "Ollama not installed. Run ./scripts/setup.sh first."
        fi
    fi
    REQUIRED_MODELS=("$DEFAULT_LLM_MODEL" "$DEFAULT_EMBED_MODEL")
    MISSING_MODELS=()
    for model in "${REQUIRED_MODELS[@]}"; do
        if ! ollama list 2>/dev/null | grep -q "^${model}"; then
            MISSING_MODELS+=("$model")
        fi
    done
    if [ ${#MISSING_MODELS[@]} -gt 0 ]; then
        fail "Missing required Ollama models: ${MISSING_MODELS[*]}. Run ./scripts/setup.sh to pull them."
    fi
    ;;

# ── LMForge ──────────────────────────────────────────────────────────────────
lmforge)
    if ! command -v lmforge &> /dev/null; then
        fail "lmforge binary not found. Run ./scripts/setup-lmforge.sh first."
    fi
    if ! curl -s http://localhost:11430/health > /dev/null 2>&1; then
        log "LMForge not running — starting daemon..."
        lmforge start &
        # Wait up to 20s for the daemon to be ready
        for i in $(seq 1 20); do
            if curl -s http://localhost:11430/health > /dev/null 2>&1; then
                ok "LMForge daemon ready at :11430"; break
            fi
            [ $i -eq 20 ] && fail "LMForge did not start in time. Check: lmforge logs"
            sleep 1
        done
    else
        ok "LMForge already running at :11430"
    fi
    # Verify the configured LLM_MODEL is known to LMForge
    _LLM_MODEL="${LLM_MODEL:-}"
    if [ -n "$_LLM_MODEL" ]; then
        if curl -s http://localhost:11430/v1/models 2>/dev/null | grep -q "$_LLM_MODEL"; then
            ok "Model '$_LLM_MODEL' available in LMForge"
        else
            echo ""
            echo "  ⚠  Model '$_LLM_MODEL' not found in LMForge."
            echo "     Run ./scripts/setup-lmforge.sh to pull it."
            echo ""
            read -p "  Press Enter to continue anyway, or Ctrl+C to abort..."
        fi
    fi
    ;;

# ── vLLM / External ──────────────────────────────────────────────────────────
vllm|external)
    log "LLM_ENGINE=$LLM_ENGINE — skipping local engine check. Ensure your engine is running at LLM_CHAT_URL=${LLM_CHAT_URL:-<not set>}"
    ;;
esac

# =============================================================================
# Build (optional)
# =============================================================================

if [ "$DO_BUILD" = true ]; then
    echo "Building images..."
    # shellcheck disable=SC2086
    docker compose $COMPOSE_FILES build
    echo ""
fi

# Ensure generated.env exists so `docker compose` can load the full project config.
# The real values are written in Phase 6 after Terraform runs.
# setup.sh creates this stub on first-time setup; this is a safety net for
# cases where the file was deleted (e.g. manual Zitadel DB reset).
GENERATED_ENV="config/zitadel/generated.env"
if [ ! -f "$GENERATED_ENV" ]; then
    mkdir -p "$(dirname "$GENERATED_ENV")"
    cat > "$GENERATED_ENV" <<'EOF'
# Auto-generated by start.sh via Terraform — do not edit manually.
# This stub allows `docker compose` commands to run before first boot.
ZITADEL_CLIENT_ID=
ZITADEL_SERVICE_ACCOUNT_PAT=
ZITADEL_PROJECT_ID=
ZITADEL_ACTIONS_SIGNING_KEY=
EOF
fi

# =============================================================================
# Phase 1: Start backing infrastructure services
# =============================================================================

echo "Starting backing infrastructure services..."
# shellcheck disable=SC2086
docker compose $COMPOSE_FILES up -d postgres redis minio qdrant clickhouse langfuse-web langfuse-worker infinity

log "Waiting for Postgres..."
for i in $(seq 1 30); do
    if docker compose exec -T postgres pg_isready -U docintel > /dev/null 2>&1; then
        ok "Postgres ready"; break
    fi
    [ $i -eq 30 ] && fail "Postgres timed out. Check: docker compose logs postgres"
    sleep 3
done

log "Waiting for MinIO..."
for i in $(seq 1 20); do
    if curl -sf http://localhost:19000/minio/health/live > /dev/null 2>&1; then
        ok "MinIO ready"; break
    fi
    [ $i -eq 20 ] && fail "MinIO timed out. Check: docker compose logs minio"
    sleep 3
done

log "Waiting for Qdrant..."
for i in $(seq 1 20); do
    if curl -sf http://localhost:6333/healthz > /dev/null 2>&1; then
        ok "Qdrant ready"; break
    fi
    [ $i -eq 20 ] && fail "Qdrant timed out. Check: docker compose logs qdrant"
    sleep 3
done

# =============================================================================
# Phase 2: Terraform infra stack (MinIO buckets + Qdrant collections)
# =============================================================================

echo ""
echo "Provisioning infrastructure (MinIO + Qdrant)..."
tofu -chdir=terraform/stacks/infra init -input=false > /dev/null
tofu -chdir=terraform/stacks/infra apply -auto-approve -input=false \
    -var-file="../../environments/dev.infra.tfvars"
ok "Infrastructure provisioned."

# =============================================================================
# Phase 3: Start Zitadel services + docintel-actions in key-pending mode
#
# docintel-actions starts WITHOUT its signing key (generated.env is still
# empty at this point).  It enters key-pending mode: /health returns 200 so
# Docker marks it healthy and Zitadel's DNS lookup resolves the hostname
# during target registration, but /claims returns 503 until the service is
# restarted with the real key in Phase 6.
# =============================================================================

echo ""
echo "Starting Zitadel services..."
# shellcheck disable=SC2086
docker compose $COMPOSE_FILES up -d zitadel-api zitadel-login zitadel-proxy docintel-actions

log "Waiting for zitadel-proxy healthy (first boot may take 2-3 min)..."
for i in $(seq 1 72); do
    if curl -sf http://localhost:9095/debug/healthz > /dev/null 2>&1; then
        ok "Zitadel ready"; break
    fi
    [ $i -eq 72 ] && fail "Zitadel timed out after 6 min. Check: docker compose logs zitadel-api"
    printf "."
    sleep 5
done
echo ""

log "Waiting for docintel-actions (key-pending mode)..."
for i in $(seq 1 20); do
    status=$(docker inspect --format='{{.State.Health.Status}}' docintel-docintel-actions-1 2>/dev/null || echo "missing")
    if [ "$status" = "healthy" ]; then
        ok "docintel-actions ready (key-pending — will be restarted with key in Phase 6)"; break
    fi
    [ $i -eq 20 ] && fail "docintel-actions timed out. Check: docker compose logs docintel-actions"
    sleep 3
done

# =============================================================================
# Phase 4: Terraform identity stack (Zitadel orgs, project, users, app)
# =============================================================================

echo ""
echo "Provisioning Zitadel identity resources..."
ADMIN_PAT_FILE="config/zitadel/bootstrap/admin.pat"
log "Waiting for bootstrap admin PAT..."
for i in $(seq 1 30); do
    if [ -f "$ADMIN_PAT_FILE" ] && [ -s "$ADMIN_PAT_FILE" ]; then
        break
    fi
    [ $i -eq 30 ] && fail "Bootstrap admin PAT not found at $ADMIN_PAT_FILE after 90s"
    sleep 3
done

# ── Stale-state detection ──────────────────────────────────────────────────
# Zitadel always writes admin.pat fresh when the DB is re-initialized.
# If admin.pat is newer than the last Terraform apply (terraform.tfstate),
# the DB was wiped (manually or via cleanup) — state references dead resource
# IDs and must be cleared before apply.
IDENTITY_STATE="terraform/stacks/identity/terraform.tfstate"
if [ -f "$IDENTITY_STATE" ] && [ "$ADMIN_PAT_FILE" -nt "$IDENTITY_STATE" ]; then
    log "Zitadel DB was re-initialized since last Terraform apply — clearing stale identity state..."
    rm -f "$IDENTITY_STATE" "${IDENTITY_STATE}.backup" \
          config/zitadel/actions-target-id \
          config/zitadel/actions-signing-key
    ok "Stale state cleared. Terraform will create all identity resources fresh."
fi

ZITADEL_BOOTSTRAP_PAT=$(cat "$ADMIN_PAT_FILE")
tofu -chdir=terraform/stacks/identity init -input=false > /dev/null
tofu -chdir=terraform/stacks/identity apply -auto-approve -input=false \
    -var-file="../../environments/dev.identity.tfvars" \
    -var="zitadel_admin_token=$ZITADEL_BOOTSTRAP_PAT"
ok "Identity resources provisioned."

# =============================================================================
# Phase 5: Actions v2 setup (feature flag + target + executions)
# Requires instance-admin scope — use the bootstrap admin PAT written by
# zitadel-api first-instance init (ZITADEL_FIRSTINSTANCE_PATPATH).
# =============================================================================

ADMIN_PAT_FILE="config/zitadel/bootstrap/admin.pat"
ACTIONS_TARGET_ID_FILE="config/zitadel/actions-target-id"
ACTIONS_SIGNING_KEY_FILE="config/zitadel/actions-signing-key"
ZITADEL_URL="http://localhost:9095"

log "Waiting for admin PAT (bootstrap)..."
for i in $(seq 1 30); do
    if [ -f "$ADMIN_PAT_FILE" ] && [ -s "$ADMIN_PAT_FILE" ]; then
        break
    fi
    [ $i -eq 30 ] && fail "Admin PAT not found at $ADMIN_PAT_FILE"
    sleep 3
done
ADMIN_PAT=$(cat "$ADMIN_PAT_FILE")
ok "Admin PAT loaded."

echo ""
echo "Setting up Zitadel Actions v2..."

# Enable Actions v2 feature flag (idempotent — 400 "No changes" is acceptable)
curl -s -X PUT "$ZITADEL_URL/v2/features/instance" \
    -H "Authorization: Bearer $ADMIN_PAT" \
    -H "Content-Type: application/json" \
    -d '{"actions": true}' > /dev/null
ok "Actions v2 feature enabled."

ACTIONS_TARGET_ID=""
ACTIONS_SIGNING_KEY=""

# Re-use existing target on idempotent re-runs
if [ -f "$ACTIONS_TARGET_ID_FILE" ]; then
    stored_id=$(cat "$ACTIONS_TARGET_ID_FILE")
    if [ -n "$stored_id" ] && curl -sf "$ZITADEL_URL/v2/actions/targets/$stored_id" \
        -H "Authorization: Bearer $ADMIN_PAT" | grep -q '"target"' 2>/dev/null; then
        ACTIONS_TARGET_ID="$stored_id"
        ACTIONS_SIGNING_KEY=$(cat "$ACTIONS_SIGNING_KEY_FILE" 2>/dev/null || echo "")
        ok "Actions target already exists: $ACTIONS_TARGET_ID"
    fi
fi

if [ -z "$ACTIONS_TARGET_ID" ]; then
    log "Registering Actions v2 target..."
    RESP=$(curl -sf -X POST "$ZITADEL_URL/v2/actions/targets" \
        -H "Authorization: Bearer $ADMIN_PAT" \
        -H "Content-Type: application/json" \
        -d '{
            "name": "DocIntel Custom Claims",
            "restCall": {"interruptOnError": false},
            "endpoint": "http://docintel-actions:8090/claims",
            "timeout": "10s"
        }')
    ACTIONS_TARGET_ID=$(echo "$RESP" | jq -r '.id // empty')
    ACTIONS_SIGNING_KEY=$(echo "$RESP" | jq -r '.signingKey // empty')
    [ -n "$ACTIONS_TARGET_ID" ] || fail "Failed to register Actions v2 target. Response: $RESP"
    echo "$ACTIONS_TARGET_ID" > "$ACTIONS_TARGET_ID_FILE"
    echo "$ACTIONS_SIGNING_KEY" > "$ACTIONS_SIGNING_KEY_FILE"
    ok "Actions target registered: $ACTIONS_TARGET_ID"
fi

for fn in preaccesstoken preuserinfo; do
    curl -sf -X PUT "$ZITADEL_URL/v2/actions/executions" \
        -H "Authorization: Bearer $ADMIN_PAT" \
        -H "Content-Type: application/json" \
        -d "{\"condition\": {\"function\": {\"name\": \"$fn\"}}, \"targets\": [\"$ACTIONS_TARGET_ID\"]}" > /dev/null
    ok "Execution set: $fn"
done

# =============================================================================
# Phase 6: Write generated.env from Terraform outputs + actions signing key
# =============================================================================

echo ""
echo "Writing config/zitadel/generated.env..."

TF_OUTPUTS=$(tofu -chdir=terraform/stacks/identity output -json)
CLIENT_ID=$(echo "$TF_OUTPUTS" | jq -r '.client_id.value')
PROJECT_ID=$(echo "$TF_OUTPUTS" | jq -r '.project_id.value')
SA_PAT=$(echo "$TF_OUTPUTS" | jq -r '.service_account_pat.value')
E2E_SA_KEY=$(echo "$TF_OUTPUTS" | jq -r '.e2e_sa_key_json.value')

cat > config/zitadel/generated.env <<EOF
# Auto-generated by start.sh — do not edit manually.
ZITADEL_CLIENT_ID=${CLIENT_ID}
ZITADEL_PROJECT_ID=${PROJECT_ID}
ZITADEL_SERVICE_ACCOUNT_PAT=${SA_PAT}
ZITADEL_ACTIONS_SIGNING_KEY=${ACTIONS_SIGNING_KEY}
E2E_SA_KEY_FILE=config/zitadel/e2e-sa-key.json
E2E_TENANT_ID=e2e
EOF
ok "generated.env written."

# Write E2E service account key (JSON) — used by run_tests.py for JWT Bearer auth
echo "$E2E_SA_KEY" > config/zitadel/e2e-sa-key.json
chmod 600 config/zitadel/e2e-sa-key.json
ok "e2e-sa-key.json written (mode 600)."

# Restart docintel-actions so it picks up ZITADEL_ACTIONS_SIGNING_KEY from
# the freshly written generated.env and exits key-pending mode.
docker compose restart docintel-actions > /dev/null
log "Waiting for docintel-actions to come back with signing key..."
for i in $(seq 1 20); do
    status=$(docker inspect --format='{{.State.Health.Status}}' docintel-docintel-actions-1 2>/dev/null || echo "missing")
    if [ "$status" = "healthy" ]; then
        ok "docintel-actions ready (signing key active)"; break
    fi
    [ $i -eq 20 ] && fail "docintel-actions timed out after key restart. Check: docker compose logs docintel-actions"
    sleep 3
done

# =============================================================================
# Phase 7: Start remaining application services
# =============================================================================

echo ""
echo "Starting application services..."
# shellcheck disable=SC2086
docker compose $COMPOSE_FILES up -d

# =============================================================================
# Wait for application services
# =============================================================================

echo ""
printf "  API Gateway: "
for i in $(seq 1 30); do
    if curl -s http://localhost:8080/actuator/health > /dev/null 2>&1; then
        echo "ready"; break
    fi
    [ $i -eq 30 ] && echo "starting... (check logs: docker compose logs api-gateway)" && break
    sleep 2
done

printf "  Ingestion Service: "
for i in $(seq 1 60); do
    status=$(docker inspect --format='{{.State.Health.Status}}' docintel-ingestion-service-1 2>/dev/null || echo "missing")
    if [ "$status" = "healthy" ]; then
        echo "ready"; break
    fi
    [ $i -eq 60 ] && echo "timeout (check logs: docker compose logs ingestion-service)" && break
    sleep 2
done

printf "  RAG Service: "
for i in $(seq 1 60); do
    status=$(docker inspect --format='{{.State.Health.Status}}' docintel-rag-service-1 2>/dev/null || echo "missing")
    if [ "$status" = "healthy" ]; then
        echo "ready"; break
    fi
    [ $i -eq 60 ] && echo "timeout (check logs: docker compose logs rag-service)" && break
    sleep 2
done

printf "  Web UI: "
for i in $(seq 1 30); do
    if curl -s http://localhost:3001 > /dev/null 2>&1; then
        echo "ready"; break
    fi
    [ $i -eq 30 ] && echo "timeout (check logs: docker compose logs web-ui)" && break
    sleep 2
done

# =============================================================================
# Done
# =============================================================================

if [[ "$OSTYPE" == "darwin"* ]]; then
    open http://localhost:3001
elif command -v xdg-open &> /dev/null; then
    xdg-open http://localhost:3001
elif command -v wslview &> /dev/null; then
    wslview http://localhost:3001
fi

echo ""
echo "================================================"
echo "  DocIntel Started"
echo "================================================"
echo ""
echo "  Service              URL"
echo "  -------------------  ---------------------------------"
echo "  Web UI               http://localhost:3001"
echo "  API Gateway          http://localhost:8080"
echo "  Ingestion Service    http://localhost:8001"
echo "  RAG Service          http://localhost:8000"
echo "  Langfuse             http://localhost:3000             (admin@docintel.local / admin123)"
echo "  MinIO Console        http://localhost:19001            (minioadmin / minioadmin)"
echo "  Qdrant               http://localhost:6333"
echo ""
echo "  Authentication (Zitadel):"
echo "  Zitadel UI     http://localhost:9095"
echo "  Admin login:   ${ZITADEL_ADMIN_USERNAME:-zitadel-admin}@docintel.localhost / ${ZITADEL_ADMIN_PASSWORD:-DocIntel@zitadel2024!}"
echo ""
echo "  Users:"
echo "    diadmin     / Diadmin@123     — Platform Admin    (org: platform)"
echo "    alphaadmin  / Alphaadmin@123  — Tenant Admin      (org: alpha)"
echo "    alphauser   / Alphauser@123   — Tenant User       (org: alpha)"
echo "    betaadmin   / Betaadmin@123   — Tenant Admin      (org: beta)"
echo "    betauser    / Betauser@123    — Tenant User       (org: beta)"
echo ""
echo "  Commands:"
echo "    ./scripts/stop.sh              Stop (preserves data)"
echo "    ./scripts/logs.sh debug        View query path logs"
echo "    ./scripts/start.sh --build     Rebuild after code changes"
echo "    ./scripts/cleanup.sh --all     Remove everything"
echo ""
